import type { Tour } from '@/types';

const tours: Tour[] = [
  {
    id: '1',
    name: 'Kyoto Cultural Expedition',
    destination: 'Japan',
    type: 'Cultural',
    duration: 7,
    price: 2500,
    description: 'Immerse yourself in the ancient culture of Kyoto. Visit serene temples, walk through bamboo groves, and experience a traditional tea ceremony.',
    itinerary: [
      { day: 1, activity: 'Arrival in Kyoto, check-in to Ryokan' },
      { day: 2, activity: 'Visit Kinkaku-ji (Golden Pavilion) and Ryoan-ji Temple' },
      { day: 3, activity: 'Explore Arashiyama Bamboo Grove and Tenryu-ji Temple' },
      { day: 4, activity: 'Gion district tour and traditional tea ceremony' },
      { day: 5, activity: 'Day trip to Fushimi Inari Shrine' },
      { day: 6, activity: 'Free day for shopping or personal exploration' },
      { day: 7, activity: 'Departure' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1730724376888-8222a5c0ca62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxKYXBhbiUyMEN1bHR1cmFsfGVufDB8fHx8MTc1MjYyMjkwOXww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Swiss Alps Adventure',
    destination: 'Switzerland',
    type: 'Adventure',
    duration: 10,
    price: 4000,
    description: 'Embark on an exhilarating adventure through the Swiss Alps. Hike stunning trails, paraglide over valleys, and enjoy breathtaking mountain views.',
    itinerary: [
      { day: 1, activity: 'Arrival in Interlaken' },
      { day: 2, activity: 'Hiking in the Jungfrau region' },
      { day: 3, activity: 'Paragliding over Interlaken' },
      { day: 4, activity: 'Train journey to Zermatt' },
      { day: 5, activity: 'View the Matterhorn and hike local trails' },
      { day: 6, activity: 'Explore Gorner Gorge' },
      { day: 7, activity: 'Travel to Lucerne' },
      { day: 8, activity: 'Lake Lucerne boat trip and Mount Pilatus' },
      { day: 9, activity: 'Free day in Lucerne' },
      { day: 10, activity: 'Departure from Zurich' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1671730068364-e3e8e19f9578?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxTd2l0emVybGFuZCUyMEFkdmVudHVyZXxlbnwwfHx8fDE3NTI2MjI5MDl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.9,
  },
  {
    id: '3',
    name: 'Tuscan Culinary Journey',
    destination: 'Italy',
    type: 'Culinary',
    duration: 5,
    price: 2200,
    description: 'Indulge in the flavors of Tuscany. Participate in cooking classes, visit local wineries, and savor authentic Italian cuisine in the heart of the countryside.',
    itinerary: [
      { day: 1, activity: 'Arrival in Florence, welcome dinner' },
      { day: 2, activity: 'Tuscan cooking class at a farmhouse' },
      { day: 3, activity: 'Chianti wine tasting tour' },
      { day: 4, activity: 'Explore Siena and San Gimignano' },
      { day: 5, activity: 'Departure' },
    ],
    availability: false,
    image: 'https://images.unsplash.com/photo-1628007485200-89988400dd54?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxJdGFseSUyMEN1bGluYXJ5fGVufDB8fHx8MTc1MjYyMjkwOXww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.7,
  },
  {
    id: '4',
    name: 'Maldives Tropical Relaxation',
    destination: 'Maldives',
    type: 'Relaxation',
    duration: 8,
    price: 5500,
    description: 'Escape to a paradise of white-sand beaches and crystal-clear waters. Relax in an overwater bungalow, snorkel among vibrant coral reefs, and enjoy ultimate tranquility.',
    itinerary: [
        { day: 1, activity: 'Arrival at Malé airport, speedboat transfer to resort' },
        { day: 2, activity: 'Relax on the beach, enjoy resort amenities' },
        { day: 3, activity: 'Guided snorkeling tour' },
        { day: 4, activity: 'Sunset dolphin cruise' },
        { day: 5, activity: 'Spa and wellness day' },
        { day: 6, activity: 'Private beach dinner' },
        { day: 7, activity: 'Free day for watersports or relaxation' },
        { day: 8, activity: 'Departure' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1675623185255-df77eccf5015?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxNYWxkaXZlcyUyMFJlbGF4YXRpb258ZW58MHx8fHwxNzUyNjIyOTA5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.9,
  },
  {
    id: '5',
    name: 'Patagonia Hiking Trek',
    destination: 'Chile',
    type: 'Adventure',
    duration: 12,
    price: 4800,
    description: "Discover the rugged beauty of Torres del Paine National Park. This challenging trek offers stunning glaciers, pristine lakes, and iconic mountain peaks.",
    itinerary: [
      { day: 1, activity: 'Arrival in Punta Arenas, transfer to Puerto Natales' },
      { day: 2, activity: 'Enter Torres del Paine, begin W-Trek' },
      { day: 3, activity: 'Hike to the base of the towers' },
      { day: 4, activity: 'Hike along Lake Nordenskjöld' },
      { day: 5, activity: 'Trek into the French Valley' },
      { day: 6, activity: 'Hike to Paine Grande and Grey Lake' },
      { day: 7, activity: 'Grey Glacier viewpoint hike' },
      { day: 8, activity: 'Catamaran across Pehoé Lake, return to Puerto Natales' },
      { day: 9, activity: 'Rest day in Puerto Natales' },
      { day: 10, activity: 'Day trip to Balmaceda and Serrano Glaciers' },
      { day: 11, activity: 'Explore local culture and cuisine' },
      { day: 12, activity: 'Departure from Punta Arenas' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1587901314925-a74af83d9d2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxDaGlsZSUyMEFkdmVudHVyZXxlbnwwfHx8fDE3NTI2MjI5MDl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 5.0,
  },
  {
    id: '6',
    name: 'Santorini Sunset Escape',
    destination: 'Greece',
    type: 'Relaxation',
    duration: 4,
    price: 1800,
    description: 'Experience the magic of Santorini. Watch iconic sunsets from Oia, explore charming villages, and relax on unique volcanic sand beaches.',
    itinerary: [
        { day: 1, activity: 'Arrival in Santorini, transfer to Oia' },
        { day: 2, activity: 'Explore Fira and local villages' },
        { day: 3, activity: 'Catamaran cruise to hot springs and Red Beach' },
        { day: 4, activity: 'Departure' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1634664375986-f327f01154e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxHcmVlY2UlMjBSZWxheGF0aW9ufGVufDB8fHx8MTc1MjYyMjkwOXww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4.8,
  },
  {
    id: '7',
    name: 'Bali One Life Adventure',
    destination: 'Indonesia',
    type: 'Adventure',
    duration: 10,
    price: 3200,
    description: 'From serene temples to active volcanoes, experience the best of Bali. Surf, hike, and find your zen in this island paradise.',
    itinerary: [
      { day: 1, activity: 'Arrival in Denpasar, transfer to Ubud' },
      { day: 2, activity: 'Tegalalang Rice Terrace and Monkey Forest' },
      { day: 3, activity: 'Mount Batur sunrise hike' },
      { day: 4, activity: 'Ubud market and cooking class' },
      { day: 5, activity: 'Travel to Seminyak' },
      { day: 6, activity: 'Surfing lesson at Kuta Beach' },
      { day: 7, activity: 'Tanah Lot temple at sunset' },
      { day: 8, activity: 'Day trip to Nusa Penida' },
      { day: 9, activity: 'Beach club and relaxation' },
      { day: 10, activity: 'Departure' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    rating: 4.9,
  },
  {
    id: '8',
    name: 'Brooklyn Beach Resort Tour',
    destination: 'Indonesia',
    type: 'Relaxation',
    duration: 10,
    price: 2800,
    description: 'Relax and unwind at a luxury beach resort in Brooklyn. Enjoy pristine beaches, world-class dining, and rejuvenating spa treatments.',
    itinerary: [
      { day: 1, activity: 'Arrival and check-in' },
      { day: 2, activity: 'Beach relaxation and swimming' },
      { day: 3, activity: 'Couples massage and spa day' },
      { day: 4, activity: 'Gourmet dining experience' },
      { day: 5, activity: 'Yoga and meditation session' },
      { day: 6, activity: 'Island hopping tour' },
      { day: 7, activity: 'Water sports activities' },
      { day: 8, activity: 'Local market visit' },
      { day: 9, activity: 'Farewell dinner on the beach' },
      { day: 10, activity: 'Departure' },
    ],
    availability: true,
    image: 'https://images.unsplash.com/photo-1507525428034-b723a9ce6893?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    rating: 4.7
  }
];

export const getTours = (): Tour[] => tours;

export const getTourById = (id: string): Tour | undefined => tours.find(tour => tour.id === id);
